#!/bin/bash
# ══════════════════════════════════════════════════════════════
#  Open Agents — One-Line Installer (Linux / macOS / WSL)
#
#  Usage:
#    curl -fsSL https://raw.githubusercontent.com/robit-man/oa-install/main/install.sh | bash
#
#  What it does:
#    1. Installs Docker (if missing)
#    2. Installs NVIDIA Container Toolkit (if GPU present, Linux only)
#    3. Builds the OA Docker image
#    4. Creates the `oa-docker` launcher command
#    5. Launches OA in an interactive container
#
#  Environment variables:
#    OA_MODEL    — Default model to pull (default: qwen3:4b)
#    OA_VERSION  — OA npm version (default: latest)
#    OA_WORKSPACE — Host directory to mount as /workspace (default: $HOME/oa-workspace)
#    OA_GPU      — GPU mode: auto, nvidia, none (default: auto)
# ══════════════════════════════════════════════════════════════
set -e

GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

OA_MODEL="${OA_MODEL:-qwen3:4b}"
OA_VERSION="${OA_VERSION:-latest}"
OA_WORKSPACE="${OA_WORKSPACE:-$HOME/oa-workspace}"
OA_GPU="${OA_GPU:-auto}"
IMAGE_NAME="open-agents"
CONTAINER_NAME="oa"

echo -e "${CYAN}"
echo "  ╔══════════════════════════════════════════╗"
echo "  ║   Open Agents — Docker Installer         ║"
echo "  ╚══════════════════════════════════════════╝"
echo -e "${NC}"

# ── Detect platform ──
OS="$(uname -s)"
ARCH="$(uname -m)"
echo -e "Platform: ${GREEN}${OS} ${ARCH}${NC}"

# ── Step 1: Docker ──
if command -v docker &>/dev/null; then
  echo -e "${GREEN}Docker: $(docker --version)${NC}"
else
  echo -e "${YELLOW}Installing Docker...${NC}"
  case "$OS" in
    Linux)
      curl -fsSL https://get.docker.com | sh
      sudo systemctl enable --now docker
      sudo usermod -aG docker "$USER"
      echo -e "${YELLOW}NOTE: You may need to log out and back in for Docker group permissions.${NC}"
      ;;
    Darwin)
      echo -e "${RED}Docker Desktop required on macOS.${NC}"
      echo "Download from: https://docs.docker.com/desktop/install/mac-install/"
      echo "After installing Docker Desktop, re-run this script."
      exit 1
      ;;
    *)
      echo -e "${RED}Unsupported OS: $OS${NC}"
      exit 1
      ;;
  esac
fi

# ── Step 2: NVIDIA Container Toolkit (Linux + GPU) ──
HAS_GPU=false
GPU_FLAGS=""

if [ "$OA_GPU" = "none" ]; then
  echo -e "${YELLOW}GPU: disabled by OA_GPU=none${NC}"
elif [ "$OS" = "Linux" ] && command -v nvidia-smi &>/dev/null; then
  HAS_GPU=true
  GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1)
  echo -e "${GREEN}GPU detected: ${GPU_NAME}${NC}"

  # Install NVIDIA Container Toolkit if missing
  if ! dpkg -l nvidia-container-toolkit &>/dev/null 2>&1; then
    echo -e "${YELLOW}Installing NVIDIA Container Toolkit...${NC}"
    curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | \
      sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
    curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
      sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
      sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
    sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
    sudo nvidia-ctk runtime configure --runtime=docker
    sudo systemctl restart docker
  fi
  GPU_FLAGS="--gpus all"
elif [ "$OS" = "Darwin" ]; then
  echo -e "${YELLOW}GPU: macOS uses Metal via Ollama natively (no Docker GPU passthrough)${NC}"
else
  echo -e "${YELLOW}GPU: not detected — running CPU-only${NC}"
fi

# ── Step 3: Create workspace ──
mkdir -p "$OA_WORKSPACE"
echo -e "Workspace: ${GREEN}${OA_WORKSPACE}${NC} (mounted as /workspace)"

# ── Step 4: Build Docker image ──
echo -e "\n${CYAN}Building OA Docker image...${NC}"

# Download Dockerfile + entrypoint if not in repo
TMPDIR=$(mktemp -d)
REPO_URL="https://raw.githubusercontent.com/robit-man/oa-install/main"

if [ -f "$(dirname "$0")/Dockerfile" ]; then
  # Running from cloned repo
  BUILD_DIR="$(dirname "$0")"
else
  # Running from curl pipe — download files
  curl -fsSL "$REPO_URL/Dockerfile" -o "$TMPDIR/Dockerfile"
  curl -fsSL "$REPO_URL/entrypoint.sh" -o "$TMPDIR/entrypoint.sh"
  chmod +x "$TMPDIR/entrypoint.sh"
  BUILD_DIR="$TMPDIR"
fi

docker build \
  --build-arg OA_VERSION="$OA_VERSION" \
  -t "$IMAGE_NAME" \
  "$BUILD_DIR"

rm -rf "$TMPDIR" 2>/dev/null || true

# ── Step 5: Create launcher script ──
LAUNCHER="$HOME/.local/bin/oa-docker"
mkdir -p "$HOME/.local/bin"

cat > "$LAUNCHER" << 'LAUNCHER_EOF'
#!/bin/bash
# Open Agents Docker Launcher
# Generated by oa-install

IMAGE_NAME="open-agents"
CONTAINER_NAME="oa"
OA_WORKSPACE="${OA_WORKSPACE:-$HOME/oa-workspace}"
OA_MODEL="${OA_MODEL:-qwen3:4b}"

# Detect GPU
GPU_FLAGS=""
if command -v nvidia-smi &>/dev/null && [ "$(uname -s)" = "Linux" ]; then
  GPU_FLAGS="--gpus all"
fi

# Stop existing container if running
docker rm -f "$CONTAINER_NAME" 2>/dev/null || true

# Use --network host on Linux (fastest), port mapping elsewhere (macOS/WSL)
NETWORK_FLAGS="--network host"
if [ "$(uname -s)" = "Darwin" ]; then
  NETWORK_FLAGS="-p 11434:11434 -p 11435:11435"
fi

exec docker run -it --rm \
  --name "$CONTAINER_NAME" \
  $GPU_FLAGS \
  $NETWORK_FLAGS \
  -e "OA_MODEL=$OA_MODEL" \
  -e "TERM=$TERM" \
  -e "COLORTERM=${COLORTERM:-truecolor}" \
  -v "$OA_WORKSPACE:/workspace" \
  -v "$HOME/.ollama:/root/.ollama" \
  -v "$HOME/.open-agents:/root/.open-agents" \
  "$IMAGE_NAME" "$@"
LAUNCHER_EOF

chmod +x "$LAUNCHER"

# Add ~/.local/bin to PATH if not already
if ! echo "$PATH" | grep -q "$HOME/.local/bin"; then
  for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
    if [ -f "$rc" ]; then
      echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$rc"
    fi
  done
  export PATH="$HOME/.local/bin:$PATH"
fi

# ── Step 6: Done! ──
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║       Installation Complete!                  ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  Launch:     ${CYAN}oa-docker${NC}"
echo -e "  API mode:   ${CYAN}oa-docker oa serve${NC}"
echo -e "  Shell:      ${CYAN}oa-docker bash${NC}"
echo -e "  Workspace:  ${CYAN}${OA_WORKSPACE}${NC}"
echo -e "  GPU:        ${CYAN}${HAS_GPU:+enabled}${HAS_GPU:-cpu-only}${NC}"
echo ""
echo -e "  ${YELLOW}Starting OA now...${NC}"
echo ""

# Launch!
exec "$LAUNCHER"
